project_id = "pnabdsgbkvriwevcksca"

[functions.token-scanner]
verify_jwt = false

[functions.auto-sniper]
verify_jwt = false

[functions.auto-exit]
verify_jwt = false

[functions.risk-check]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false

[functions.api-secrets]
verify_jwt = false

[functions.trade-execution]
verify_jwt = false

[functions.confirm-transaction]
verify_jwt = false
